version: '3.8'

services:
  web:
    image: fanlab-web:0.1  
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
      - ./docker/certs:/etc/nginx/certs
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
      - db
      - phpmyadmin
      - code-editor
      #  - metabase
      - selenium
      - redis
    networks:
      - backend
      - private

  php:
    image: fanlab-php-supervisor:0.7
    volumes:
      - .:/app
      - backups:/backups
    networks:
      - private
    restart: unless-stopped
    
  db:
    image: mariadb:10.8.3
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_USER: ''
      MYSQL_PASSWORD: ''
      MYSQL_DATABASE: ''
    ports:
      - "3306:3306"
    networks:
      - private

  

 

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_ABSOLUTE_URI: https://${DOMAIN}/${PREFIX}/pma/
      PMA_HOST: db
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - private

  redis:
    image: docker.io/bitnami/redis:7.0
    environment:
      REDIS_PASSWORD: 'redispassword'
    ports:
      - "6379:6379"
    networks:
      - private
    restart: unless-stopped

  selenium:
        image: 'selenium/standalone-chrome'
        volumes:
            - '/dev/shm:/dev/shm'
        shm_size: '2gb'
        ports:
           - 7900
           - 5900
        networks:
            - private
        restart: unless-stopped

  node:
        image: node:20.0.0
        volumes:
            - .:/app
            - backups:/backups
        networks:
             - private
        restart: unless-stopped
        command: "bash -c 'sleep infinity'"
        tty: true
        user: 1111:1111

  markserv:
        image: fanlab/markserv:0.1
        restart: unless-stopped
        networks:
           - private
        volumes:
          - ./resources/docs/Skeletor:/usr/src/app/md/
  
  code-editor:
        image: fanlab-codercom-code-server:0.6
        networks:
          - private
        user: "1111:1111"
        volumes:
          - .:/home/coder/project/
          - ./code-editor-ssh/:/home/coder/.ssh/
        restart: unless-stopped

volumes:
    mysqldata: {}
    backups: {}
networks:
  private:
    driver: bridge
  backend:
    external: true
    name: backend