name: Skeletor basic tests in docker compose
 
on: [push, workflow_dispatch]
 
jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

 
      - name: Prepare Laravel Application
        run: |
          cp .env.docker .env
          id
          chown 1111:1111 -R *
          chown 1111:1111 -R .*
 
      - name: Start docker compose stack
        run: docker compose --file ./docker/docker-compose.yml up -d

      - name: Run tests
        run: docker compose --file ./docker/docker-compose.yml exec -it php php artisan test