name: Skeletor basic tests in docker compose
 
on: [push, workflow_dispatch]
 
jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
 
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none
 
      - name: Prepare Laravel Application
        run: |
          cp .env.testing.slug .env
          composer dump-autoload
          php artisan key:generate
 
      - name: Start docker compose stack
        run: docker compose --file ./docker/docker-compose.yml up -d

      - name: Run tests
        run: docker compose --file ./docker/docker-compose.yml exec -it php php artisan test